### ISSUE TITLE
conda  parameter error 'conda: error: unrecognized arguments: --no-capture-output'

### ISSUE THREAD

**Issue by tanyingjia** [Merck/matcher#10]
When I use this command，‘docker-compose up'，there was a mistake. I checked my version of conda, it has the--no-capture-output parameter, I don't know why it can't recognize this parameter when I run this command.

Attaching to matcher-backend-1, matcher-database-1, matcher-frontend-1
matcher-database-1  |
matcher-database-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
matcher-database-1  |
matcher-database-1  | 2023-11-14 17:17:40.592 UTC [1] LOG:  starting PostgreSQL 13.5 (Debian 13.5-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
matcher-database-1  | 2023-11-14 17:17:40.592 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
matcher-database-1  | 2023-11-14 17:17:40.592 UTC [1] LOG:  listening on IPv6 address "::", port 5432
matcher-database-1  | 2023-11-14 17:17:40.595 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
matcher-database-1  | 2023-11-14 17:17:40.598 UTC [26] LOG:  database system was shut down at 2023-11-14 17:13:13 UTC
matcher-database-1  | 2023-11-14 17:17:40.601 UTC [1] LOG:  database system is ready to accept connections
matcher-backend-1   |
matcher-backend-1   | usage: conda [-h] [-V] command ...
matcher-backend-1   | conda: error: unrecognized arguments: --no-capture-output
matcher-backend-1 exited with code 1
matcher-frontend-1  | usage: conda [-h] [-V] command ...
matcher-frontend-1  | conda: error: unrecognized arguments: --no-capture-output

**Comment by hooveran** [comment]
Hi @tanyingjia ,

Thanks for reporting this issue.

I think the problem may be caused by the version of the condaforge/miniforge3 docker image that you are currently using. The conda errors you are seeing are within Docker containers. If you checked your version of conda outside of the containers, the conda version would not necessarily be or act the same.

I tried to fix this problem by specifying tags for the condaforge/miniforge3 base images that Matcher uses. That way, you and I can both try the same image versions to diagnose whether this is the issue. Could you please give the below steps a try, and let me know what happens? When I run the below steps, the matcher application works as expected.

1. Stop your currently running matcher application and remove the db volumes by running `docker-compose down --volumes` in the matcher directory. Note this will delete your current matcher DB
2. Get the updated code, which now has tagged base images: `git checkout -b hotfix/conda-image-tag origin/hotfix/conda-image-tag`
3. Build new Matcher docker images starting from the tagged base images: `docker-compose build --no-cache`
4. Launch and test the application like normal, with `docker-compose up`
