### ISSUE TITLE
Installation Issue - Please help me

### ISSUE THREAD

**Issue by sitanshubhunia** [Merck/matcher#5]
###  First of all, thanks for your valuable repository.
I am working on Windows 10 environment. After cloning repository, I got the same error as described in #1. Again, follow the resolve steps. But after that I am getting the folloing error

![matcher](https://user-images.githubusercontent.com/840684/235632271-86588cbb-3783-46bf-9ba6-10d146376db4.png)

Regards,
Sitanshu

**Comment by hooveran** [comment]
Hi @sitanshubhunia ,

Thanks for reporting this issue.

As you highlight in your image and red arrow/box, the issue is with the `/bin/bash^M` text.

My hypothesis is that git on Windows automatically added Windows-specific line endings to the text files of the code you cloned. Afterwards, these files are no longer compatible with the Linux environment inside the backend container.

To fix, after shutting down the matcher containers (with Ctrl+C or otherwise), navigate to the matcher parent directory and please try the below steps.

1. `docker compose down --volumes` The --volumes flag is important for removing database data saved by Docker, such that when you recreate a new database container in the future, the database config can start from scratch
2. `git config --global core.autocrlf false` This command is expected to prevent automatic conversion of files to windows format when you download files with git
3. `git checkout -- . && git reset --hard HEAD` This command is expected to convert the matcher code back to having the original Linux-style format, such that they will work inside the containers
4. `docker compose up --force-recreate` Recreate the containers from scratch
5. Wait to see the following in your terminal: `matcher-backend-1   | INFO:     Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)`
6. Navigate to localhost:8000 in Chrome or Edge

**Comment by sitanshubhunia** [comment]
Many thanks for help @hooveran .
### **I have successfully installed and run it as per your instructions.**
FYI
![matcher_done](https://user-images.githubusercontent.com/840684/235925617-90e2746e-d722-468f-90a1-19ab5e80c2f7.png)

One thing now I noticed that when it's running from localhost its working fine. But when I put machine's ip (i.e. host machine ip) some issue is arise  i.e when I access it from remotely from browser. ** I accepted it may be due to my lack of knowledge. If you help me on this regards it will be very much appreciated.** 

_**Note: Please check red box portion in image**_

### **From localhost it's working fine.**
![working_on_localhost](https://user-images.githubusercontent.com/840684/235926613-d6be5316-62b4-40a5-95b8-33829736a846.png)

### **when I tried it from remotely with host machine's ip**

![from_another_ip](https://user-images.githubusercontent.com/840684/235927657-1e56e4fc-c29d-40c8-87ae-631dce86f11f.png)

**Comment by hooveran** [comment]
I can't guarantee support of setups other than the provided localhost config, because by default we are trying to keep our codebase simple.

Could I ask what is your objective with using the host ip? Are you trying to serve the application to other users over a network?

With that being said, for your use case of using the host machine's ip instead of localhost, to start, you could try modifying the [docker-compose.yml](https://github.com/Merck/matcher/blob/main/docker-compose.yml) file, by changing the EXTERNAL_BACKEND_URL and EXTERNAL_FRONTEND_URL to have your ip address instead of localhost. These are environment variables that get propagated to the Dash app in [pairplot.py](https://github.com/Merck/matcher/blob/main/frontend/pairplot.py) (lines 18-20), and also to the frontend Flask API in [frontend_api.py](https://github.com/Merck/matcher/blob/main/frontend/frontend_api.py) (lines 9-10), and also to [matcher.js](https://github.com/Merck/matcher/blob/main/frontend/js/matcher.js) via frontend_api.py through templating.

**Comment by sitanshubhunia** [comment]
@hooveran Thanks for help. Basically I installed it on a server machine. After that I wants to browse it from remote machine. **Now I understood, it will be better to browse it where I install this application**.  Thanks again for guidance.

Regards,
Sitanshu Bhunia
